services:
  api:
    build:
      context: .
      dockerfile: device-api/Dockerfile
    container_name: devices-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devices
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  postgres:
    image: postgres:16
    container_name: devices-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devices
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
