version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-devices
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devicesdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
